/** Order numbers: `GLM-YYYYMMDD-NNNN` (IST date + 4-digit sequence), generated by `next_order_number()` in SQL. */

export const ORDER_NUMBER_RE = /^GLM-(\d{8})-(\d{4})$/;

export function isOrderNumber(value: string): boolean {
  return ORDER_NUMBER_RE.test(value.trim());
}

/**
 * Normalises user input ("glm 20261002 0001", "GLM202610020001", " glm-20261002-0001 ") to the
 * canonical `GLM-20261002-0001`. Returns null when the input cannot be an order number.
 */
export function formatOrderNumber(raw: string): string | null {
  const compact = raw.toUpperCase().replace(/[\s\-_#]/g, "");
  const m = compact.match(/^GLM(\d{8})(\d{4})$/);
  if (!m) return null;
  const candidate = `GLM-${m[1]}-${m[2]}`;
  return orderNumberDate(candidate) ? candidate : null;
}

/** Calendar date (UTC midnight) encoded in an order number; null when the date part is invalid. */
export function orderNumberDate(orderNumber: string): Date | null {
  const m = orderNumber.trim().match(ORDER_NUMBER_RE);
  if (!m) return null;
  const y = Number(m[1].slice(0, 4));
  const mo = Number(m[1].slice(4, 6));
  const d = Number(m[1].slice(6, 8));
  if (mo < 1 || mo > 12 || d < 1 || d > 31) return null;
  const date = new Date(Date.UTC(y, mo - 1, d));
  if (date.getUTCMonth() !== mo - 1 || date.getUTCDate() !== d) return null;
  return date;
}

/** Short display form for compact UIs: "#0001 · 2 Oct". */
export function shortOrderNumber(orderNumber: string): string {
  const m = orderNumber.match(ORDER_NUMBER_RE);
  if (!m) return orderNumber;
  const date = orderNumberDate(orderNumber);
  const day = date ? date.toLocaleDateString("en-IN", { day: "numeric", month: "short", timeZone: "UTC" }) : m[1];
  return `#${m[2]} · ${day}`;
}
